[package]
name = "cmdutils"
version = "0.0.3"
edition = "2021"
authors = ["Aarav Maloo"]
[dependencies]
clap = { version = "4", features = ["derive"] }
image = "0.25"
oxipng = { version = "9", default-features = false, features = ["zopfli", "parallel"] }
resvg = "0.43"
kamadak-exif = "0.6"
printpdf = "0.7"
base64 = "0.22"
glob = "0.3"
ab_glyph = "0.2"
fontdb = "0.16"
imageproc = "0.25"
md-5 = "0.10"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
