name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add AUR_SSH_PRIVATE_KEY="$AUR_SSH_PRIVATE_KEY" PAT_TOKEN="$PAT_TOKEN" --repo aaravmaloo/cmdutils
